### ISSUE TITLE
[GCM] Package Design Quality Metrics | Part 1

### ISSUE THREAD

**Issue by g10z3r** [4rchr4y/go-code-metric#2]
### Subtasks:
- [x] Implement a metric to calculate **Abstractness**
- [x] Implement a metric to calculate **Instability**
- [x] Implement a metric to calculate **Cohesion** (LCOM, LCOM 96b, etc...)
- [x] Implement a metric to calculate **Distance from Main Sequence**
- [x] Implement tests for all written functions

### Links:
Repo - https://github.com/4rchr4y/go-code-metric
