### ISSUE TITLE
[GCM] Package Design Quality Metrics | Part 2

### ISSUE THREAD

**Issue by g10z3r** [4rchr4y/go-code-metric#6]
### Subtasks
- [x] Implement a metric to calculate **Coupling**
- [x] Implement a metric to calculate **AMC** (Average Method Complexity)
- [x] Implement a metric to calculate **WMC** (Weighted Methods per Class)
- [x] Implement a metric to calculate **CAM** (Cohesion Among Methods)
- [x] Implement a metric to calculate **Reusability Index**
- [x] Implement/Update of documentation (explanations for this are in a **Requirements** block)

### Requirements
1. Maintain documentation for each metric function in the `README.md` file.
   How to maintain documentation for the metrics calculation function? Should be included in the description of each metric:
   - Metric name (Metric Full Name)
   - Metric formula
   - Metric formula explanation

#### Example

$$
\text{Reusability Index} = w_1 \times C + w_2 \times (1 - K) + w_3 \times T + w_4 \times D
$$

**Where:**

$C$ - cohesion,
$K$ - coupling,
$T$ - testability,
$D$ - documentation,
$w_1, w_2, w_3, w_4$ — weighting coefficients (the weighting coefficients are determined by the user).

2. Maintain documentation for each metric function in the source code.

   #### Example
   ```golang
   // Desc
   // ...
   // [link to the section describing this metric in README.md file]
   func CalcLCOMb96() {
      ...
   }
   ```

### References
- https://valerio-terragni.github.io/assets/pdf/terragni-icpc-2020.pdf
- https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7359354
